name: trsonn.com
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
logo: http://trsonn.com/logo.png
show_downloads: false
title: trsonn.com
description: hire me!

theme: jekyll-theme-minimal
